services:
  postgres:
    image: postgres:latest
    container_name: vulnsync-postgres
    environment:
      POSTGRES_DB: vulnsync
      POSTGRES_USER: vulnsync
      POSTGRES_PASSWORD: vulnsync
    ports:
      - "5432:5432"
    volumes:
      - vulnsync-pgdata:/var/lib/postgresql

  backend:
    build:
      context: ./vulnsync-backend
    container_name: vulnsync-backend
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./vulnsync-frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: vulnsync-frontend

    env_file:
      - .env
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: vulnsync-nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro

volumes:
  vulnsync-pgdata:
