services:
  postgres:
    image: postgres:latest
    container_name: vulnsync-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "9876:5432"
    volumes:
      - vulnsync-pgdata:/var/lib/postgresql

  backend:
    build:
      context: ./vulnsync-backend
      args:
        ENV: ${ENV}
        USE_NEXUS: ${USE_NEXUS}
        NEXUS_NPM_REGISTRY: ${NEXUS_NPM_REGISTRY}
        DATABASE_URL: ${DATABASE_URL}
    container_name: vulnsync-backend
    env_file:
      - .env

    depends_on:
      - postgres

  frontend:
    build:
      context: ./vulnsync-frontend
      args:
        ENV: ${ENV}
        USE_NEXUS: ${USE_NEXUS}
        NEXUS_NPM_REGISTRY: ${NEXUS_NPM_REGISTRY}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED}
    container_name: vulnsync-frontend
    env_file:
      - .env
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: vulnsync-nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./nginx/ssl:/etc/nginx/ssl:ro

volumes:
  vulnsync-pgdata:
